<a href="https://colab.research.google.com/github/istahadul07/Python_withML_BlackOrigin/blob/main/Class11%5Bnumpy%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
from time import process_time

#list vs numpy time taken

In [4]:

lists=[i for i in range(1000)]
start=process_time()
lists=[i+5 for i in lists]
end=process_time()
print(end-start)

0.00013547400000013532


In [5]:
#list vs numpy time taken
lists=[i for i in range(1000)]
start=process_time()
lists=[i+5 for i in lists]
end=process_time()
print(end-start)

0.00021272799999993985


In [6]:
numpy_array=np.array([i for i in range(1000)])
start=process_time()
numpy_array=numpy_array+5
end=process_time()
print(end-start)

0.00020768299999995854


In [7]:
list1=[1,2,3,4,5]
print(list)
type(list)

<class 'list'>


type

In [17]:
#numpy
import importlib
import numpy as np
importlib.reload(np)

np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
print(type(np_array))


[1 2 3 4 5]
<class 'numpy.ndarray'>


/usr/lib/python3.11/importlib/__init__.py:169: UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.
  _bootstrap._exec(spec, module)


What a.shape means
shape is an attribute of NumPy arrays.
It tells you the dimensions of the array as a tuple.
The tuple has:
Number of elements along each axis.For a 1D array, it’s (n,) where n is the length of the array.


In [24]:
#creating a one dimensional array.
a=np.array([1,2,3,4,5,7])
print(a)
a.shape


[1 2 3 4 5 7]


(6,)

In [28]:
b=np.array([(1,2,3,4),(5,2,1,3)])
print(b)
b.shape

[[1 2 3 4]
 [5 2 1 3]]


(2, 4)

In [31]:
#float
c=np.array([(1.1,2.5,3.6,4),(5,2,1,3)],dtype=float)
print(c)
c.shape

[[1.1 2.5 3.2 4. ]
 [5.  2.  1.  3. ]]


(2, 4)

#Initial Placeholders in numpy Array.

In [32]:
x=np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


For particular value

In [35]:
z=np.full((3,4),6)
print(z)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


creating an indentity matrix

In [36]:
p=np.eye(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Random float value in array

In [37]:
r=np.random.random((3,4))
print(r)

[[0.4209657  0.79561067 0.72521971 0.45623619]
 [0.96139617 0.2407452  0.67493939 0.17116905]
 [0.3060723  0.52009078 0.19020364 0.99433521]]


Random integer value array within specific range

In [39]:
q=np.random.randint(10,150,(3,5))
print(q)

[[ 21 112  98  96  86]
 [ 13 138 113  58  34]
 [ 78  88  79  48 128]]


Analyzing a numpy array
note:
1. .shape
Definition: A tuple that tells you the size of the array along each axis.
What it shows: The length (number of elements) in each dimension.
example:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)   # (2, 3) → 2 rows, 3 columns
2. .ndim
Definition: An integer that tells you the number of dimensions (axes) in the array.
What it shows: The rank of the array
Example:
print(a.ndim)    # 2 → because it’s 2D (rows & columns)

In [50]:
#checking dimension
xy=np.array([(1,2,3,4),(5,2,1,3)])
print(xy)
xy.shape
#checking number of elements
xy.size
#checking datatype in array
xy.dtype
#checking number of dimension
xy.ndim

[[1 2 3 4]
 [5 2 1 3]]


2

various operation in array.

In [55]:
#numpy
a=np.random.randint(10,100,(3,3))
b=np.random.randint(10,100,(3,3))
print(a)
print(b)

#sum
print("Sum:",a+b)
#multiply
print("Multiply:",a*b)
#divide
print("Divide:",a/b)

#array manipulation
result=np.transpose(a)
print(result)

[[33 45 62]
 [60 16 71]
 [22 30 66]]
[[27 83 75]
 [32 17 88]
 [75 52 19]]
Sum: [[ 60 128 137]
 [ 92  33 159]
 [ 97  82  85]]
Multiply: [[ 891 3735 4650]
 [1920  272 6248]
 [1650 1560 1254]]
Divide: [[1.22222222 0.54216867 0.82666667]
 [1.875      0.94117647 0.80681818]
 [0.29333333 0.57692308 3.47368421]]
[[33 60 22]
 [45 16 30]
 [62 71 66]]
